// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StartPagePlus
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageString = "863d9c86-c92d-4ce0-87c6-087e3a0b6cbf";
        public static Guid Package = new Guid(PackageString);

        public const string PackageCommandSetString = "915ab04f-9aa8-4d24-b06b-bb1524e3c7bf";
        public static Guid PackageCommandSet = new Guid(PackageCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PackageGroup = 0xB000;
        public const int ViewStartPagePlus = 0x0210;
        public const int StartPagePlusOptions = 0x0215;
    }
}