// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StartPagePlus
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageString = "d260ddba-7a30-4094-a145-23a778a11d04";
        public static Guid Package = new Guid(PackageString);

        public const string PackageCommandSetString = "bd83d0a2-ec30-4f7a-a13e-ddf411cd63fd";
        public static Guid PackageCommandSet = new Guid(PackageCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PackageGroup = 0xB000;
        public const int PackageOptionsCommand = 0x0215;
    }
}