// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StartPagePlus
{
    internal sealed partial class Vsix
    {
        public const string Id = "3E9E5D1B-8919-4240-8660-C9AD234891BB";
        public const string Name = "Start Page+";
        public const string Description = @"Bring back Start Page! (a document tab, NOT a modal window)";
        public const string Language = "en-US";
        public const string Version = "0.1.0.7";
        public const string Author = "Yann Duran";
        public const string Tags = "Start Page+, start-page-plus, StartPagePlus, start page, start-page, startpage, luminous, yannduran, yd";
    }
}
