// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StartPagePlus
{
    internal sealed partial class Vsix
    {
        public const string Id = "AC56C545-C0F5-4AC2-B319-BAF9877B050B";
        public const string Name = "Start Page+";
        public const string Description = @"Bring back Start Page! (a document tab, NOT a modal window)";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Yann Duran";
        public const string Tags = "start page plus; startpageplus; start-page-plus; yannduran; yd; luminous";
    }
}
